export const NAME_SPACE = "Home";

export const GET_MESSAGES = NAME_SPACE + "_GET_MESSAGES";
export const GET_MESSAGES_FAIL = NAME_SPACE + "_GET_MESSAGES_FAIL";
export const GET_MESSAGES_SUCCESS = NAME_SPACE + "_GET_MESSAGES_SUCCESS";
export const HIDE_UNDO = NAME_SPACE + "_HIDE_UNDO";
export const REMOVE_MESSAGE = NAME_SPACE + "_REMOVE_MESSAGE";
